In [1]:
import polars as pl

exp_a_metric = "/data1/ccs_data/202603-good-ecoli-data/20260311_240601Y0012_Run0003_adapter_metric/20260311_240601Y0012_Run0003.newmodel.stage1.baseline.smc_all_reads.aligned.metric.csv"
exp_b_metric = "/data1/ccs_data/202603-good-ecoli-data/20260311_240601Y0012_Run0003_adapter_metric/20260311_240601Y0012_Run0003.newmodel.stage1.norna-nofwdrev-nopoly-fullAlignAndPlp-epo37.smc_all_reads.aligned.metric.csv"

df_a = pl.read_csv(exp_a_metric, separator="\t")
df_b = pl.read_csv(exp_b_metric, separator="\t")

df_a = df_a.filter(pl.col("subreadPasses") > 7)
df_b = df_b.filter(pl.col("subreadPasses") > 7)


df_1 = df_a.join(df_b, on="channel_id", how="inner")

print(df_1.filter(pl.col("concordance") > pl.col("concordance_right")).shape)
print(df_1.filter(pl.col("concordance") < pl.col("concordance_right")).shape)
print(df_1.filter(pl.col("concordance") == pl.col("concordance_right")).shape)

df = df_a.join(df_b, on="channel_id", how="inner").filter(
    pl.col("concordance") > pl.col("concordance_right")).filter(
        pl.col("refStart") == pl.col("refStart_right")).filter(
            pl.col("refEnd") == pl.col("refEnd_right"))
        
        


print(df_a.head(10))
print(df_b.head(10))

print(df.head(10))

(12657, 37)
(8449, 37)
(104493, 37)
shape: (10, 19)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ channel_id ┆ readLength ┆ subreadPa ┆ queryConv ┆ … ┆ refEnd ┆ mmRefPosi ┆ insRefPos ┆ delRefPos │
│ ---        ┆ Bp         ┆ sses      ┆ erage     ┆   ┆ ---    ┆ tions     ┆ itions    ┆ itions    │
│ i64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ i64    ┆ ---       ┆ ---       ┆ ---       │
│            ┆ i64        ┆ i64       ┆ f64       ┆   ┆        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 410803     ┆ 883        ┆ 14        ┆ 0.9467724 ┆ … ┆ 837    ┆           ┆           ┆ 451       │
│ 515302     ┆ 421        ┆ 30        ┆ 0.793349  ┆ … ┆ 334    ┆           ┆           ┆           │
│ 336131     ┆ 910        ┆ 14        ┆ 0.9186813 ┆ … ┆ 838    ┆           ┆           ┆ 248,425   │
│ 109510     ┆ 651        ┆ 19        ┆ 0.7741935 ┆ … ┆ 504    ┆           ┆           ┆           │
│ 519764     ┆ 753        ┆ 9         ┆ 0.714475  ┆ … ┆ 537    ┆           ┆ 455       ┆ 301       │
│ 338409     ┆ 605        ┆ 20        ┆ 1.0       ┆ … ┆ 619    ┆           ┆           ┆           │
│ 98041      ┆ 603        ┆ 14        ┆ 1.0       ┆ … ┆ 701    ┆           ┆           ┆ 451       │
│ 492120     ┆ 1344       ┆ 8         ┆ 1.0       ┆ … ┆ 1459   ┆           ┆ 1323      ┆ 451,753,7 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ 54,1026   │
│ 43355      ┆ 817        ┆ 15        ┆ 0.99388   ┆ … ┆ 973    ┆           ┆           ┆           │
│ 486234     ┆ 850        ┆ 14        ┆ 0.9505882 ┆ … ┆ 980    ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘
shape: (10, 19)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ channel_id ┆ readLength ┆ subreadPa ┆ queryConv ┆ … ┆ refEnd ┆ mmRefPosi ┆ insRefPos ┆ delRefPos │
│ ---        ┆ Bp         ┆ sses      ┆ erage     ┆   ┆ ---    ┆ tions     ┆ itions    ┆ itions    │
│ i64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ i64    ┆ ---       ┆ ---       ┆ ---       │
│            ┆ i64        ┆ i64       ┆ f64       ┆   ┆        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 515302     ┆ 361        ┆ 30        ┆ 0.925208  ┆ … ┆ 334    ┆           ┆           ┆           │
│ 410803     ┆ 883        ┆ 14        ┆ 0.9467724 ┆ … ┆ 837    ┆           ┆           ┆ 451       │
│ 336131     ┆ 911        ┆ 14        ┆ 0.9187706 ┆ … ┆ 838    ┆           ┆           ┆ 425       │
│ 109510     ┆ 651        ┆ 19        ┆ 0.7741935 ┆ … ┆ 504    ┆           ┆           ┆           │
│ 338409     ┆ 605        ┆ 20        ┆ 1.0       ┆ … ┆ 619    ┆           ┆           ┆           │
│ 519764     ┆ 752        ┆ 9         ┆ 0.7140958 ┆ … ┆ 537    ┆           ┆           ┆           │
│ 11496      ┆ 617        ┆ 15        ┆ 0.9432739 ┆ … ┆ 584    ┆           ┆ 301       ┆ 33,58,456 │
│ 98041      ┆ 603        ┆ 14        ┆ 1.0       ┆ … ┆ 701    ┆           ┆           ┆ 451       │
│ 492120     ┆ 1344       ┆ 8         ┆ 1.0       ┆ … ┆ 1459   ┆           ┆           ┆ 451,759,1 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ 026       │
│ 43355      ┆ 814        ┆ 15        ┆ 0.997543  ┆ … ┆ 973    ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘
shape: (10, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ channel_i ┆ readLengt ┆ subreadPa ┆ queryConv ┆ … ┆ refEnd_ri ┆ mmRefPosi ┆ insRefPos ┆ delRefPo │
│ d         ┆ hBp       ┆ sses      ┆ erage     ┆   ┆ ght       ┆ tions_rig ┆ itions_ri ┆ sitions_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ht        ┆ ght       ┆ right    │
│ i64       ┆ i64       ┆ i64       ┆ f64       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 397973    ┆ 815       ┆ 18        ┆ 0.9042945 ┆ … ┆ 1403      ┆           ┆ 805       ┆ 828      │
│ 285154    ┆ 421       ┆ 31        ┆ 0.9976247 ┆ … ┆ 1138      ┆           ┆           ┆ 844      │
│ 220075    ┆ 889       ┆ 10        ┆ 1.0       ┆ … ┆ 1683      ┆           ┆           ┆ 1597     │
│ 253125    ┆ 791       ┆ 16        ┆ 1.0       ┆ … ┆ 2165      ┆           ┆ 1941      ┆          │
│ 242702    ┆ 408       ┆ 24        ┆ 1.0       ┆ … ┆ 2581      ┆           ┆           ┆          │
│ 237316    ┆ 1361      ┆ 9         ┆ 1.0       ┆ … ┆ 3979      ┆           ┆ 3586,3906 ┆ 2746     │
│ 252521    ┆ 811       ┆ 11        ┆ 1.0       ┆ … ┆ 6036      ┆           ┆           ┆ 5435,546 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 253350    ┆ 438       ┆ 22        ┆ 1.0       ┆ … ┆ 5816      ┆           ┆           ┆          │
│ 94861     ┆ 1025      ┆ 8         ┆ 1.0       ┆ … ┆ 6986      ┆           ┆           ┆ 6150,679 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ 501382    ┆ 769       ┆ 17        ┆ 1.0       ┆ … ┆ 6835      ┆           ┆ 6230      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [2]:
df_a.head(10)

shape: (10, 19)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ channel_id ┆ readLength ┆ subreadPa ┆ queryConv ┆ … ┆ refEnd ┆ mmRefPosi ┆ insRefPos ┆ delRefPos │
│ ---        ┆ Bp         ┆ sses      ┆ erage     ┆   ┆ ---    ┆ tions     ┆ itions    ┆ itions    │
│ i64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ i64    ┆ ---       ┆ ---       ┆ ---       │
│            ┆ i64        ┆ i64       ┆ f64       ┆   ┆        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 410803     ┆ 883        ┆ 14        ┆ 0.9467724 ┆ … ┆ 837    ┆           ┆           ┆ 451       │
│ 515302     ┆ 421        ┆ 30        ┆ 0.793349  ┆ … ┆ 334    ┆           ┆           ┆           │
│ 336131     ┆ 910        ┆ 14        ┆ 0.9186813 ┆ … ┆ 838    ┆           ┆           ┆ 248,425   │
│ 109510     ┆ 651        ┆ 19        ┆ 0.7741935 ┆ … ┆ 504    ┆           ┆           ┆           │
│ 519764     ┆ 753        ┆ 9         ┆ 0.714475  ┆ … ┆ 537    ┆           ┆ 455       ┆ 301       │
│ 338409     ┆ 605        ┆ 20        ┆ 1.0       ┆ … ┆ 619    ┆           ┆           ┆           │
│ 98041      ┆ 603        ┆ 14        ┆ 1.0       ┆ … ┆ 701    ┆           ┆           ┆ 451       │
│ 492120     ┆ 1344       ┆ 8         ┆ 1.0       ┆ … ┆ 1459   ┆           ┆ 1323      ┆ 451,753,7 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ 54,1026   │
│ 43355      ┆ 817        ┆ 15        ┆ 0.99388   ┆ … ┆ 973    ┆           ┆           ┆           │
│ 486234     ┆ 850        ┆ 14        ┆ 0.9505882 ┆ … ┆ 980    ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [3]:
df_b.head(10)

shape: (10, 19)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ channel_id ┆ readLength ┆ subreadPa ┆ queryConv ┆ … ┆ refEnd ┆ mmRefPosi ┆ insRefPos ┆ delRefPos │
│ ---        ┆ Bp         ┆ sses      ┆ erage     ┆   ┆ ---    ┆ tions     ┆ itions    ┆ itions    │
│ i64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ i64    ┆ ---       ┆ ---       ┆ ---       │
│            ┆ i64        ┆ i64       ┆ f64       ┆   ┆        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 515302     ┆ 361        ┆ 30        ┆ 0.925208  ┆ … ┆ 334    ┆           ┆           ┆           │
│ 410803     ┆ 883        ┆ 14        ┆ 0.9467724 ┆ … ┆ 837    ┆           ┆           ┆ 451       │
│ 336131     ┆ 911        ┆ 14        ┆ 0.9187706 ┆ … ┆ 838    ┆           ┆           ┆ 425       │
│ 109510     ┆ 651        ┆ 19        ┆ 0.7741935 ┆ … ┆ 504    ┆           ┆           ┆           │
│ 338409     ┆ 605        ┆ 20        ┆ 1.0       ┆ … ┆ 619    ┆           ┆           ┆           │
│ 519764     ┆ 752        ┆ 9         ┆ 0.7140958 ┆ … ┆ 537    ┆           ┆           ┆           │
│ 11496      ┆ 617        ┆ 15        ┆ 0.9432739 ┆ … ┆ 584    ┆           ┆ 301       ┆ 33,58,456 │
│ 98041      ┆ 603        ┆ 14        ┆ 1.0       ┆ … ┆ 701    ┆           ┆           ┆ 451       │
│ 492120     ┆ 1344       ┆ 8         ┆ 1.0       ┆ … ┆ 1459   ┆           ┆           ┆ 451,759,1 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ 026       │
│ 43355      ┆ 814        ┆ 15        ┆ 0.997543  ┆ … ┆ 973    ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [5]:
df.head(10).select(pl.col("channel_id"), pl.col("^mmRefPositions.*$"), pl.col("^insRefPositions.*$"), pl.col("^delRefPositions.*$"))

shape: (10, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ channel_id ┆ mmRefPositio ┆ mmRefPositio ┆ insRefPosit ┆ insRefPosit ┆ delRefPosit ┆ delRefPosit │
│ ---        ┆ ns           ┆ ns_right     ┆ ions        ┆ ions_right  ┆ ions        ┆ ions_right  │
│ i64        ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆ str          ┆ str          ┆ str         ┆ str         ┆ str         ┆ str         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 397973     ┆              ┆              ┆             ┆ 805         ┆             ┆ 828         │
│ 285154     ┆              ┆              ┆             ┆             ┆             ┆ 844         │
│ 220075     ┆              ┆              ┆             ┆             ┆             ┆ 1597        │
│ 253125     ┆              ┆              ┆             ┆ 1941        ┆             ┆             │
│ 242702     ┆              ┆              ┆             ┆             ┆             ┆             │
│ 237316     ┆              ┆              ┆ 3586        ┆ 3586,3906   ┆ 2748,3012   ┆ 2746        │
│ 252521     ┆              ┆              ┆             ┆             ┆ 5461        ┆ 5435,5461   │
│ 253350     ┆              ┆              ┆             ┆             ┆             ┆             │
│ 94861      ┆              ┆              ┆ 6552        ┆             ┆ 6150        ┆ 6150,6792   │
│ 501382     ┆              ┆              ┆             ┆ 6230        ┆             ┆             │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [6]:
",".join(df.head(10)["channel_id"].cast(pl.String).to_list())

'397973,285154,220075,253125,242702,237316,252521,253350,94861,501382'